# Generated by Django 4.2.11 on 2025-01-26 12:18

import core.apps.account.models
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='username')),
                ('name', models.CharField(max_length=125, verbose_name='name')),
                ('surname', models.CharField(max_length=125, verbose_name='surname')),
                ('gender', models.CharField(choices=[('MLE', 'Male'), ('FML', 'Female'), ('NBN', 'Non-binary')], max_length=10)),
                ('profile_image', models.ImageField(default='profile_images/default.png', max_length=255, upload_to=core.apps.account.models.get_profile_image_filepath)),
                ('email', models.EmailField(max_length=125, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'unique': 'Phonenumber is already in use'}, max_length=128, null=True, region=None, unique=True, verbose_name='phone number')),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('accept', models.BooleanField(default=False, help_text='Terms and Conditions', verbose_name='accept')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('username', 'email', 'phone_number'), name='unique_undeleted_fields'),
        ),
    ]
