# Generated by Django 4.2.11 on 2025-01-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal', models.CharField(max_length=50, verbose_name='journal')),
                ('trading_model', models.CharField(max_length=50, verbose_name='trading model')),
                ('entry_model', models.CharField(max_length=50, verbose_name='entry model')),
                ('risk_appetite', models.CharField(choices=[('HIG', 'High'), ('MED', 'Medium'), ('LOW', 'Low')], max_length=3, verbose_name='risk appetite')),
                ('riskreward_profile', models.CharField(choices=[('OTT', '1:2'), ('OTR', '1:3'), ('OTF', '1:4')], max_length=3, verbose_name='reward profile')),
                ('order_type', models.CharField(choices=[('BUY', 'Buy'), ('SEL', 'Sell'), ('SLL', 'Sell limit'), ('BYL', 'Buy limit')], max_length=3, verbose_name='order type')),
                ('fill_price', models.DecimalField(blank=True, decimal_places=5, max_digits=7, null=True, verbose_name='fill price')),
                ('exit_price', models.DecimalField(blank=True, decimal_places=5, max_digits=7, null=True, verbose_name='exit price')),
                ('stoploss_price', models.DecimalField(blank=True, decimal_places=5, max_digits=7, null=True, verbose_name='fill price')),
                ('takeprofit_price', models.DecimalField(blank=True, decimal_places=5, max_digits=7, null=True, verbose_name='fill price')),
                ('execution_time', models.DateTimeField(blank=True, null=True, verbose_name='execution time')),
                ('exit_time', models.DateTimeField(blank=True, null=True, verbose_name='exit time')),
                ('outcome', models.CharField(choices=[('INP', 'In progress'), ('WIN', 'Win'), ('LOS', 'Loss')], default='INP', max_length=3, verbose_name='outcome')),
                ('trade_review', models.CharField(blank=True, max_length=250, null=True, verbose_name='trade review')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
