# Generated by Django 4.2.11 on 2025-01-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='symbol',
            field=models.CharField(default='', max_length=50, verbose_name='symbol'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trade',
            name='riskreward_profile',
            field=models.CharField(max_length=4, verbose_name='reward profile'),
        ),
    ]
