# Generated by Django 4.2.11 on 2025-01-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_trade_symbol_alter_trade_riskreward_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='exit_price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True, verbose_name='exit price'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='fill_price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True, verbose_name='fill price'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='stoploss_price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True, verbose_name='fill price'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='takeprofit_price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True, verbose_name='fill price'),
        ),
    ]
